name: river
description: A new Flutter river.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  extra_alignments: ^1.0.0+1
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  focusable_control_builder: ^1.0.1+1
  gap: ^3.0.0
  particle_field: ^1.0.0
  provider: ^6.0.5
  rnd: ^0.2.0
  vector_math: ^2.1.4
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  shaders:
    - assets/shaders/river_shader.frag
    - assets/shaders/orb_shader.frag
    - assets/shaders/learning_shader.frag
    - assets/shaders/wood_shader.frag